name: mani_skill
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - astroid=2.6.5=py38h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupy=8.3.0=py38hcaf9a05_0
  - fastrlock=0.6=py38h2531618_0
  - future=0.18.2=py38_1
  - geos=3.8.0=he6710b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - isort=5.9.2=pyhd3eb1b0_0
  - lazy-object-proxy=1.6.0=py38h27cfd23_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libspatialindex=1.9.3=h2531618_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - mccabe=0.6.1=py38_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - nccl=2.8.3.1=hcaf9a05_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=21.0=pyhd3eb1b0_0
  - pathlib2=2.3.6=py38h06a4308_2
  - pip=21.1.3=py38h06a4308_0
  - pluggy=0.13.1=py38h06a4308_0
  - py=1.10.0=pyhd3eb1b0_0
  - pylint=2.9.5=py38h06a4308_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pytest=6.2.4=py38h06a4308_2
  - python=3.8.10=h12debd9_8
  - pyyaml=5.4.1=py38h27cfd23_1
  - readline=8.1=h27cfd23_0
  - rtree=0.9.7=py38h06a4308_1
  - scipy=1.6.2=py38had2a1c9_1
  - setuptools=52.0.0=py38h06a4308_0
  - shapely=1.7.1=py38h98ec03d_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tabulate=0.8.9=py38h06a4308_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - transforms3d=0.3.1=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py38h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - addict==2.4.0
    - anyio==3.3.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==3.3.1
    - cffi==1.14.6
    - charset-normalizer==2.0.3
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - debugpy==1.4.1
    - decorator==5.0.9
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.3
    - gym==0.18.3
    - idna==3.2
    - ipykernel==6.0.3
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyter-packaging==0.10.4
    - jupyter-server==1.10.1
    - jupyterlab==3.0.16
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.6.1
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclassic==0.3.1
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.0
    - open3d==0.13.0
    - opencv-python==4.5.3.56
    - pandas==1.3.0
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pyglet==1.5.15
    - pygments==2.9.0
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyzmq==22.1.0
    - requests==2.26.0
    - requests-unixsocket==0.2.0
    - scikit-learn==0.24.2
    - send2trash==1.7.1
    - sniffio==1.2.0
    - terminado==0.10.1
    - testpath==0.5.0
    - threadpoolctl==2.2.0
    - tomlkit==0.7.2
    - tornado==6.1
    - traitlets==5.0.5
    - trimesh==3.9.24
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.1.0
    - widgetsnbextension==3.5.1
